server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password:
    url: jdbc:postgresql://localhost:5432/registration #database details
    username:
  jpa:
    hibernate:
      ddl-auto: create-drop #It is useful for testing. It means that the values we create in a database will be dropped
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

